ROR capstone project
Hadi111jafari/My-Wallet pull request #2
Opened 2022-09-11 05:10 UTC by Hadi111jafari

PR Description:
in this PR I implemented:

Splash screen
1- A simple page with the name of the Budget App and links to the sign-up and log-in pages.

Sign up and log in to pages
1- The user is able to register in the app with full name (first name and Lastname), email, and password (all mandatory).
2- The user can log into the app using email and password.
3- If the user is not logged in, they can't access pages that require the user to be logged in.

Category page
1- When the user logs in, they are presented with the categories page.
2- For each category, the user can see their name, icon, and the total amount of all the transactions that belong to that category.
3- When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
4- There is a button "add a new category" at the bottom that brings the user to the page to create a new category.

Transactions page
1- For a given category, the list of transactions is presented, ordered by the most recent.
2- At the top of the page the user can see the total amount for the category.
3- There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.
4- When the user clicks on the "Back" button (<), the user navigates to the home page.

Add a new category" page
1- The user fills out a form to create a new category, indicating their name and icon.
2- The user click (or taps) the "Save" button to create the new category, and is taken to the home page on success.
3- When the user clicks on the "Back" button (<), the user navigates to the home page.

Add a new transaction" page
1- The user fills out a form to create a new transaction with:
2- name
3- amount
4- The user click (or taps) the "Save" button to create the new category, and is taken to the transactions page for that category.
5- When the user clicks on the "Back" button (<), the user navigates to the transactions page for that category.

Testing requirements
1- Create unit and integration tests for all the most important components of your RoR application.

Technical requirements
1- Used Postgres as a database.
2- Used devise for authentication.
3- validate all user input to make sure that anyone with bad intentions cannot compromise your app.
4- The project is deployed and accessible online.
5- database schema reflects the requirements structure

2022-09-16 05:02 UTC, andersonlebon requested changes
## Hi @Hadi111jafari 

Good job so far! I know you have worked hard on making this milestone But  There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
## Required Changes ♻️

- [ ] Kindly check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-16 05:02 UTC, andersonlebon commented on app/views/devise/registrations/new.html.erb
> +<%= render "devise/shared/links" %>
- [x] Kindly make sure the user name is provided when the user is signing up as the name attribute should be present in your validation.

- [x] Kindly also follow the template design on your both registration page and login pages

![image](https://user-images.githubusercontent.com/65068771/190556208-df6e8acc-95fa-4226-8649-6ab89dcc7230.png)

2022-09-16 05:02 UTC, andersonlebon commented on app/views/groups/show.html.erb
> +</button>
- [x] Kindly display the list of all expenses related to this category/group
- [x] Also make the list follow the template design

 | the template | Your design|
--|--
![image](https://user-images.githubusercontent.com/65068771/190557040-96bdd478-0d91-4063-8334-d701c0a2e411.png) | ![image](https://user-images.githubusercontent.com/65068771/190557254-f5270c69-e741-47f6-a81d-48498e2c7865.png)

2022-09-16 05:02 UTC, andersonlebon commented on app/views/groups/index.html.erb
> +        $ <%= group.total_amount %>
- [x] Kindly make sure the total of all expenses related to each category/group is displayed here.

2022-09-16 05:02 UTC, andersonlebon commented on app/views/groups/new.html.erb
> +</section>
- [x] Kindly make sure this form looks like the original template(navigation, buttons, inputs ,,,)
- [x] Also use icons in your navigation bar
you design :
![image](https://user-images.githubusercontent.com/65068771/190558122-2169000c-32f0-40f7-af32-01c7ee541dd9.png)

2022-09-16 05:02 UTC, andersonlebon commented on app/views/expenses/new.html.erb
> +
- [x] Kindly make sure this form looks like the original template(navigation, buttons, inputs ,,,)
- [x]  Also use icons in your navigation bar

you design :

![image](https://user-images.githubusercontent.com/65068771/190558353-75092099-3ee2-4e4a-bd21-296053baa00e.png)

2022-09-16 05:02 UTC, andersonlebon commented on app/views/devise/sessions/new.html.erb
> +<%= render "devise/shared/links" %>
- [x] Kindly follow the design template here on the login page
![image](https://user-images.githubusercontent.com/65068771/190558579-fac02434-bbc4-4948-9b6d-bd0269901dd0.png)

2022-09-16 05:02 UTC, andersonlebon commented on README.md
> +```
- [ ] Kindly follow the documentation requirement and provide a video demo of your project, it should match these criterias:

![image](https://user-images.githubusercontent.com/65068771/190560265-55250963-2b37-4ef9-a403-0b778a9b4e70.png)

2022-09-17 09:42 UTC, Hadi111jafari commented
The error from deployment is from Netlify and I deployed in heroku

2022-09-17 09:44 UTC, AshakaE approved these changes
Hi @Hadi111jafari , 

Thanks for making the requested changes 👏 

### Highlights ✨ 

- Pull request 👌 
- Git flow ✅ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Proceed to the next level 👏 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-17 09:47 UTC, merged